#!/bin/bash

args=()
argsline=`echo $1 | sed "s/\;//g"`

for arg in $argsline; do
	args+=($arg)
done

printf "public Constructor ("
for ((i=0; i<${#args[@]}; i+=3)); do
	type="${args[$i+1]}"
	name="${args[$i+2]}"

	cap=`echo $name | sed 's/\(^.\)/\U\1/'`

	printf "$type p$cap"
	if [[ $i -lt $((${#args[@]}-3)) ]]; then
		printf ", "
	fi
done

printf "){\n"
for ((i=0; i<${#args[@]}; i+=3)); do
	type="${args[$i+1]}"
	name="${args[$i+2]}"

	cap=`echo $name | sed 's/\(^.\)/\U\1/'`

	printf "    $name = p$cap;\n"
done
printf "}"


for ((i=0; i<${#args[@]}; i+=3)); do
type="${args[$i+1]}"
name="${args[$i+2]}"

cap=`echo $name | sed 's/\(^.\)/\U\1/'`

printf "
public $type get$cap(){
    return $name;
}

public void set$cap($type p$cap){
    $name = p$cap;
}
"
done
